Added notifications library
siisltd/Curiosity.Utils pull request #20
Opened 2021-03-16 10:41 UTC by DevCorvette

2021-03-27 14:49 UTC, Markeli commented on src/Curiosity.Notification/Abstractions/INotificationMetadata.cs
> +        int Type { get; }
Может,  Type также сделать строкой, как и ChannelType? А то какая-то двойственность получается.

2021-03-27 14:53 UTC, Markeli requested changes
А каналы отправки EMail и SMS мы сюда не будем сразу добавлять?

2021-04-05 07:15 UTC, DevCorvette commented on src/Curiosity.Notification/Abstractions/INotificationMetadata.cs
> +        int Type { get; }
ок, пусть будет string

2021-04-05 07:16 UTC, DevCorvette commented
> А каналы отправки EMail и SMS мы сюда не будем сразу добавлять?

email добавил sms предлагаю добавить как понадобятся

2021-04-15 11:55 UTC, Markeli approved these changes

2021-04-15 13:42 UTC, merged

2021-04-15 13:43 UTC, Markeli reviewed
All is ok.