Added CuriosityWatchdog
siisltd/Curiosity.Utils pull request #31
Opened 2021-06-03 04:41 UTC by ilya-negrub

### Что сделано
 - Добавил `CuriosityWatchdog`

2021-06-03 11:32 UTC, Markeli requested changes

2021-06-03 11:32 UTC, Markeli commented on src/Curiosity.Hosting/CuriosityWatchdog.cs
> +        protected virtual async Task OnAttemptExceptionAsync(Exception e, CancellationToken stoppingToken)
Для токенов отмены лучше задавать дефолтное значение. Если кому-то токен отмены не нужен будет, то метод будет проще и легче вызывать.

2021-06-03 11:32 UTC, Markeli commented on src/Curiosity.Hosting/CuriosityWatchdog.cs
> +    /// Базовый класс для сервисов, которые выполняют какую-то функцию по таймеру.
В Utils комменты пишем на английском, open source же)

2021-06-03 11:32 UTC, Markeli commented on src/Curiosity.Hosting/CuriosityWatchdog.cs
> +        protected readonly TimeSpan _timer;
Имя не совсем корректное. Это же не timer, а некий delay. `watchdogPeriod` лучше подходит.

2021-06-03 11:32 UTC, Markeli commented on src/Curiosity.Hosting/CuriosityWatchdog.cs
> +        protected virtual async Task OnAttemptExceptionAsync(Exception e, CancellationToken stoppingToken)
Метод лучше назвать `HandleExceptionAsync`. Attempt - это попытка. А тут мы именно обрабатываем исключение. И при переопределении метода разработчик будет переопределять обработку исключения, а не попытку.

2021-06-03 11:32 UTC, Markeli commented on src/Curiosity.Hosting/CuriosityWatchdog.cs
> +        protected readonly TimeSpan _attemptTimer;
`attempTimer` тоже не очень удачное название. `exceptionDelay` лучше.

2021-06-03 11:32 UTC, Markeli commented on src/Curiosity.Hosting/CuriosityWatchdog.cs
> +        protected readonly TimeSpan _attemptTimer;
Если есть идеи, как сделать нейминг более понятным, предлагай)

2021-06-03 11:32 UTC, Markeli commented on src/Curiosity.Hosting/CuriosityWatchdog.cs
> +        protected readonly ILogger _logger;
Тут надо использовать свойства, а не поля класса. Поля класса наследник сможет изменить, нужно, чтобы это все было наследникам доступо только для чтения. Иначе смысл передачи значений для них через конструктор вообще пропадает.

2021-06-03 11:37 UTC, ilya-negrub commented on src/Curiosity.Hosting/CuriosityWatchdog.cs
> +        protected virtual async Task OnAttemptExceptionAsync(Exception e, CancellationToken stoppingToken)
Кода делал параметр думал об этом, но не понял каким значением устанавливать?

2021-06-03 11:43 UTC, ilya-negrub commented on src/Curiosity.Hosting/CuriosityWatchdog.cs
> +        protected virtual async Task OnAttemptExceptionAsync(Exception e, CancellationToken stoppingToken)
Поставил 10 минут

2021-06-03 11:50 UTC, Markeli commented on src/Curiosity.Hosting/CuriosityWatchdog.cs
> +        protected virtual async Task OnAttemptExceptionAsync(Exception e, CancellationToken stoppingToken)
Эм, просто `CancellationToken token = default`)

2021-06-03 11:54 UTC, ilya-negrub commented on src/Curiosity.Hosting/CuriosityWatchdog.cs
> +        protected readonly TimeSpan _attemptTimer;
Как на счет `handleExceptionPeriod`?

2021-06-03 12:11 UTC, ilya-negrub commented on src/Curiosity.Hosting/CuriosityWatchdog.cs
> +        protected readonly ILogger _logger;
Так оно же `readonly`, его ни кто не может изменить, кроме как в конструкторе типа в котором определено поле

2021-06-03 12:11 UTC, ilya-negrub commented on src/Curiosity.Hosting/CuriosityWatchdog.cs
> +        protected virtual async Task OnAttemptExceptionAsync(Exception e, CancellationToken stoppingToken)
Готово

2021-06-03 12:11 UTC, ilya-negrub commented on src/Curiosity.Hosting/CuriosityWatchdog.cs
> +        protected readonly TimeSpan _timer;
Готово

2021-06-03 12:12 UTC, ilya-negrub commented on src/Curiosity.Hosting/CuriosityWatchdog.cs
> +    /// Базовый класс для сервисов, которые выполняют какую-то функцию по таймеру.
Ща туту будет гугл транслит ))

2021-06-03 12:12 UTC, ilya-negrub commented on src/Curiosity.Hosting/CuriosityWatchdog.cs
> +    /// Базовый класс для сервисов, которые выполняют какую-то функцию по таймеру.
Готово

2021-06-03 12:13 UTC, ilya-negrub commented on src/Curiosity.Hosting/CuriosityWatchdog.cs
> +        protected virtual async Task OnAttemptExceptionAsync(Exception e, CancellationToken stoppingToken)
Упс, не так понял ))

2021-06-03 12:15 UTC, ilya-negrub commented on src/Curiosity.Hosting/CuriosityWatchdog.cs
> +        protected virtual async Task OnAttemptExceptionAsync(Exception e, CancellationToken stoppingToken)
А в конструкторе параметру "интервала ошибки" поставить значение по умолчанию? Я просто про это подумал и сделал ))

2021-06-03 15:51 UTC, Markeli commented on src/Curiosity.Hosting/CuriosityWatchdog.cs
> +        protected virtual async Task OnAttemptExceptionAsync(Exception e, CancellationToken stoppingToken)
А, и я тебя недопонял. Это тоже хорошо, оставляй)

2021-06-03 15:52 UTC, Markeli commented on src/Curiosity.Hosting/CuriosityWatchdog.cs
> +        protected readonly TimeSpan _attemptTimer;
`exceptionDelay` лучше, т.к. период значит, что у тебя что-то выполняет периодически. А тут именно задержка в случае ошибки.

2021-06-03 15:53 UTC, Markeli commented on src/Curiosity.Hosting/CuriosityWatchdog.cs
> +        protected readonly ILogger _logger;
Этот момент упустил. Но обычно потомкам дают именно свойства, а не поля, т.к. потом легче рефачить.

2021-06-04 12:31 UTC, Markeli approved these changes

2021-06-04 12:34 UTC, merged